export enum ProductType {
	STANDARD = 'STANDARD',         // Classic all-purpose bikes
	CRUISER = 'CRUISER',           // Harley-style low seat, long body
	SPORT = 'SPORT',               // High-speed, performance bikes
	TOURING = 'TOURING',           // Long-distance comfort motorcycles
	DUAL_SPORT = 'DUAL_SPORT',     // On-road + off-road
	ADVENTURE = 'ADVENTURE',       // Big off-road touring bikes
	OFF_ROAD = 'OFF_ROAD',         // Dirt bikes, motocross
	SCOOTER = 'SCOOTER',           // Lightweight, automatic transmission
	MOPED = 'MOPED',               // Small engine, pedal-like
	CAFE_RACER = 'CAFE_RACER',     // Retro-style lightweight racer
}

export enum ProductStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum ProductLocation {
	ALABAMA = 'ALABAMA',
	ALASKA = 'ALASKA',
	ARIZONA = 'ARIZONA',
	ARKANSAS = 'ARKANSAS',
	CALIFORNIA = 'CALIFORNIA',
	COLORADO = 'COLORADO',
	CONNECTICUT = 'CONNECTICUT',
	DELAWARE = 'DELAWARE',
	FLORIDA = 'FLORIDA',
	GEORGIA = 'GEORGIA',
	HAWAII = 'HAWAII',
	IDAHO = 'IDAHO',
	ILLINOIS = 'ILLINOIS',
	INDIANA = 'INDIANA',
	IOWA = 'IOWA',
	KANSAS = 'KANSAS',
	KENTUCKY = 'KENTUCKY',
	LOUISIANA = 'LOUISIANA',
	MAINE = 'MAINE',
	MARYLAND = 'MARYLAND',
	MASSACHUSETTS = 'MASSACHUSETTS',
	MICHIGAN = 'MICHIGAN',
	MINNESOTA = 'MINNESOTA',
	MISSISSIPPI = 'MISSISSIPPI',
	MISSOURI = 'MISSOURI',
	MONTANA = 'MONTANA',
	NEBRASKA = 'NEBRASKA',
	NEVADA = 'NEVADA',
	NEW_HAMPSHIRE = 'NEW_HAMPSHIRE',
	NEW_JERSEY = 'NEW_JERSEY',
	NEW_MEXICO = 'NEW_MEXICO',
	NEW_YORK = 'NEW_YORK',
	NORTH_CAROLINA = 'NORTH_CAROLINA',
	NORTH_DAKOTA = 'NORTH_DAKOTA',
	OHIO = 'OHIO',
	OKLAHOMA = 'OKLAHOMA',
	OREGON = 'OREGON',
	PENNSYLVANIA = 'PENNSYLVANIA',
	RHODE_ISLAND = 'RHODE_ISLAND',
	SOUTH_CAROLINA = 'SOUTH_CAROLINA',
	SOUTH_DAKOTA = 'SOUTH_DAKOTA',
	TENNESSEE = 'TENNESSEE',
	TEXAS = 'TEXAS',
	UTAH = 'UTAH',
	VERMONT = 'VERMONT',
	VIRGINIA = 'VIRGINIA',
	WASHINGTON = 'WASHINGTON',
	WEST_VIRGINIA = 'WEST_VIRGINIA',
	WISCONSIN = 'WISCONSIN',
	WYOMING = 'WYOMING'
}
